name: tags

on: workflow_dispatch # Trigger on any new tag push (e.g., v1.1.0)

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3
    - name: Generate changelog
      id: changelog
      uses: metcalfc/changelog-generator@v4.3.1 #TODO: bump this after release
      with:
        myToken: ${{ secrets.GITHUB_TOKEN }}
        head-ref: ${{ github.sha }} #add 'origin/` in front of your branch name
        base-ref: 'v0.6.0'
        fetch: false
    - name: Get the changelog
      run: |
        cat << "EOF"
        ${{ steps.changelog.outputs.changelog }}
        EOF
