name: tags

on: workflow_dispatch # Trigger on any new tag push (e.g., v1.1.0)

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3
    - name: Generate Release Notes
      uses: gableroux/generate-github-release-notes@v0.1.2
      with:
        repository: ${{ github.repository }}
        base_tag: v0.2.0
        head_tag: ${{ github.sha }}
        github_token: ${{ secrets.GITHUB_TOKEN }}
