name: tags

on: workflow_dispatch # Trigger on any new tag push (e.g., v1.1.0)

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3
    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: v0.6.0
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Generate Release Notes
      id: release_notes
      uses: gableroux/generate-github-release-notes@v0.1.2
      with:
         repository: ${{ github.repository }}
         base_tag: v0.5.0
         head_tag: v0.6.0
         github_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
          # this is the description of the release from previous step
        body: ${{ steps.release_notes.outputs.notes }}
        tag_name: v0.6.0
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
